import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import logo from 'public/logo.svg';

export const Page: React.FC = ({ children }) => (
  <>
    <Head>
      <title>Switch EV Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="bg-yellow-100 min-h-screen font-sans">
      <header className="py-6 border-b border-yellow-200">
        <div className="container mx-auto">
          <Image src={logo} alt="Switch EV logo" />
        </div>
      </header>

      <main className="container mx-auto py-6">{children}</main>
    </div>
  </>
);
